package entity

import "time"

// MatchKPI mirrors the match_stats table generated by triggers.
type MatchKPI struct {
	MatchID         string    `json:"match_id"`
	TotalMoves      int       `json:"total_moves"`
	Errors          int       `json:"errors"`
	AvgTimeMs       int       `json:"avg_time_ms"`
	BuclicidadAvg   float64   `json:"buclicidad_avg"`
	BranchFactorAvg float64   `json:"branch_factor_avg"`
	ComputedAt      time.Time `json:"computed_at"`
}
